import queue
from typing import Iterator, List
from events import Event, MarketEvent
from data_handler import DataHandler

class EventQueue:
    """
    Priority Queue for events ordered by timestamp.
    Uses a sequence number as a tie-breaker to preserve FIFO order
    and avoid comparing Event objects directly.
    """
    def __init__(self):
        self._queue = []
        self._sequence = 0
        self.current_time = None

    def put(self, event: Event):
        # Prevent lookahead / time travel
        if self.current_time is not None and event.timestamp < self.current_time:
            raise ValueError(
                f"Time-travel detected! Cannot push event {event} "
                f"with timestamp {event.timestamp} because current simulation time is {self.current_time}"
            )
        import heapq
        heapq.heappush(self._queue, (event.timestamp, self._sequence, event))
        self._sequence += 1

    def get(self) -> Event:
        if not self._queue:
            raise queue.Empty
        import heapq
        timestamp, seq, event = heapq.heappop(self._queue)
        self.current_time = timestamp
        return event

    def empty(self) -> bool:
        return len(self._queue) == 0

    def qsize(self) -> int:
        return len(self._queue)


class BacktestEngine:
    """
    Manages the event queue and the main event loop, orchestrating
    the flow of events between DataHandler, Strategy, Portfolio, and Execution.
    """
    def __init__(self, data_handler: DataHandler):
        self.data_handler = data_handler
        self.events = EventQueue()
        self.data_stream: Iterator[MarketEvent] = None
        self.handlers_by_type = {}
        self.data_stream_exhausted = False
        self.last_market_time = None

    def register_handler(self, handler, event_types: list = None):
        """
        Register a handler that responds to specific event types.
        If event_types is None, we automatically route based on common types.
        """
        if event_types is None:
            from events import MarketEvent, SignalEvent, OrderEvent, FillEvent
            
            # Auto-route standard classes to minimize dispatch overhead
            class_name = handler.__class__.__name__
            if "Strategy" in class_name:
                event_types = [MarketEvent]
            elif "Portfolio" in class_name:
                event_types = [MarketEvent, SignalEvent, FillEvent]
            elif "Execution" in class_name or "Simulator" in class_name:
                event_types = [MarketEvent, OrderEvent]
            else:
                # Fallback to all event types
                event_types = [MarketEvent, SignalEvent, OrderEvent, FillEvent]

        for et in event_types:
            if et not in self.handlers_by_type:
                self.handlers_by_type[et] = []
            self.handlers_by_type[et].append(handler)

    def _load_next_market_event(self):
        """Fetch the next market event from the data handler and queue it."""
        try:
            next_event = next(self.data_stream)
            self.events.put(next_event)
        except StopIteration:
            self.data_stream_exhausted = True

    def run(self):
        """Runs the main backtest event loop."""
        self.data_stream = self.data_handler.stream_data()
        self.data_stream_exhausted = False
        self.last_market_time = None
        
        # Load the very first market event to kick off the loop
        self._load_next_market_event()

        # Keep running while there are events in the queue
        while not self.events.empty():
            # Termination check: if the next scheduled event is in the future
            # and there is no more market data coming, we stop.
            next_ts = self.events._queue[0][0]
            if self.data_stream_exhausted and self.last_market_time is not None and next_ts > self.last_market_time:
                break

            event = self.events.get()
            if isinstance(event, MarketEvent):
                self.last_market_time = event.timestamp

            event_class = type(event)

            # Dispatch event only to registered handlers for this event type
            resulting_events = []
            handlers = self.handlers_by_type.get(event_class, [])
            for handler in handlers:
                new_events = handler.handle_event(event)
                if new_events:
                    if isinstance(new_events, list):
                        resulting_events.extend(new_events)
                    else:
                        resulting_events.append(new_events)

            # Queue any new events generated by the handlers
            for new_event in resulting_events:
                self.events.put(new_event)

            # If we just popped a market event, load the next one from the stream
            if isinstance(event, MarketEvent):
                self._load_next_market_event()
