from dataclasses import dataclass
from typing import Dict, Any

@dataclass
class Event:
    """Base Event class."""
    timestamp: Any  # Should be a comparable type, e.g., pd.Timestamp or datetime

@dataclass
class MarketEvent(Event):
    """
    Triggered when the data handler detects a new market update (e.g., a new bar or tick).
    """
    symbol: str
    data: Dict[str, Any]  # Contains OHLCV or tick details

    def __repr__(self):
        return f"MarketEvent(time={self.timestamp}, symbol={self.symbol}, data={self.data})"

@dataclass
class SignalEvent(Event):
    """
    Generated by Strategy objects and received by Portfolio/Execution objects.
    """
    symbol: str
    direction: str  # 'BUY', 'SELL', 'HOLD'
    strength: float = 1.0

    def __repr__(self):
        return f"SignalEvent(time={self.timestamp}, symbol={self.symbol}, direction={self.direction}, strength={self.strength})"

@dataclass
class OrderEvent(Event):
    """
    Generated by Portfolio objects and received by ExecutionHandler.
    """
    symbol: str
    order_type: str  # 'MKT', 'LMT'
    quantity: int
    direction: str  # 'BUY', 'SELL'
    price: float = 0.0

    def __repr__(self):
        return f"OrderEvent(time={self.timestamp}, symbol={self.symbol}, type={self.order_type}, qty={self.quantity}, dir={self.direction}, price={self.price})"

@dataclass
class FillEvent(Event):
    """
    Generated by ExecutionHandler when an order is executed (filled).
    """
    symbol: str
    exchange: str
    quantity: int
    direction: str  # 'BUY', 'SELL'
    fill_price: float
    commission: float = 0.0

    def __repr__(self):
        return f"FillEvent(time={self.timestamp}, symbol={self.symbol}, qty={self.quantity}, dir={self.direction}, price={self.fill_price}, commission={self.commission})"
